### ISSUE TITLE
Pensar en Costos y crear el modelo

### ISSUE THREAD

**Issue by rplusq** [rafaelqsistemas/helix-flights-backend#3]
Quedamos pendiente en pensar cómo manejar lo de los precios de sobreventa y eso, dependiendo de qué asiento compren: Primera clase o económico.

**Comment by ginacuadrado** [comment]
Consideramos colocar la sobreventa como un atributo de la entidad vuelo, que sea un boolean. Así obtendremos cuáles son los vuelos que sufrieron de esto.  

Por otra parte, consideraremos en Boleto el atributo "abordó", para saber cuáles son los pasajeros que fueron afectados y esto se obtiene observando si se llegó al máximo de pasajeros en el avión, se verá cuales pasajeros aun no han abordado, entonces se procederá a reprogramarlos o a devolver el dinero.

**Comment by ginacuadrado** [comment]
Colocaremos en "Boleto" los atributos "abordó" y "sobreventa" como boolean para resolver el problema de la sobreventa.
