### ISSUE TITLE
Chequear las relaciones actuales

### ISSUE THREAD

**Issue by rplusq** [rafaelqsistemas/helix-flights-backend#5]
Revisar las relaciones definidas en el código a través de sequelize. Si hay errores, acomodarlos.

La importancia de esto es por los múltiples cambios que hemos realizado a nuestra tabla.

**Comment by ginacuadrado** [comment]
Verificar cómo implementar los costos de los pasajes fijos. 
Verificar cómo implementar la sobreventa de pasajes.
